package ovh.heraud.testdatabuilder.generic;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * One row to insert: a {@link TestTable} plus its column values. A column
 * value is either an immediate literal or another {@link Data} (resolved to
 * that row's generated id at insert time, for foreign keys). A referenced
 * {@link Data} must already be registered on the builder (template methods
 * always create and register a parent before building a child that
 * references it), so the builder never needs to insert it out of order.
 */
public class Data {

	private final TestTable table;
	private final int index;
	private final Map<String, Object> columns = new LinkedHashMap<>();
	private Long generatedId;
	private boolean added;

	/**
	 * Same as {@link #Data(TestTable, int)}, with index {@code 0}.
	 *
	 * @param table the table this row belongs to
	 */
	public Data(TestTable table) {
		this(table, 0);
	}

	/**
	 * @param table the table this row belongs to
	 * @param index the table-scoped creation index, see {@link #getIndex()}
	 */
	Data(TestTable table, int index) {
		this.table = table;
		this.index = index;
	}

	/**
	 * Sets a column value, by raw SQL column name.
	 *
	 * @param column the SQL column name
	 * @param value  the value to bind — a literal, another {@link Data} (resolved
	 *               to its generated id at insert time), or a {@link SqlExpression}
	 * @return this {@link Data}, for chaining
	 */
	public Data setColumn(String column, Object value) {
		columns.put(column, value);
		return this;
	}

	/**
	 * Same as {@link #setColumn(String, Object)}, keyed by a {@link TestColumn}
	 * enum constant instead of a raw string.
	 *
	 * @param column the column, as a typo-safe enum constant
	 * @param value  the value to bind — see {@link #setColumn(String, Object)}
	 * @return this {@link Data}, for chaining
	 */
	public Data setColumn(TestColumn column, Object value) {
		return setColumn(column.getSqlName(), value);
	}

	/**
	 * The table this row belongs to.
	 *
	 * @return the table this row belongs to
	 */
	public TestTable getTable() {
		return table;
	}

	/**
	 * The table-scoped index this {@link Data} was created with, see
	 * {@link TestDataBuilder#newData}.
	 *
	 * @return the table-scoped creation index
	 */
	public int getIndex() {
		return index;
	}

	/**
	 * Every column value set so far.
	 *
	 * @return every column value set so far, keyed by SQL column name
	 */
	public Map<String, Object> getColumns() {
		return columns;
	}

	/**
	 * Reads back a column value set via {@link #setColumn}, for assertions.
	 *
	 * @param <T>    the expected value type, inferred at the call site
	 * @param column the SQL column name
	 * @return the value previously set for that column, or {@code null} if none
	 */
	@SuppressWarnings("unchecked")
	public <T> T getColumn(String column) {
		return (T) columns.get(column);
	}

	/**
	 * Same as {@link #getColumn(String)}, keyed by a {@link TestColumn} enum
	 * constant instead of a raw string.
	 *
	 * @param <T>    the expected value type, inferred at the call site
	 * @param column the column, as a typo-safe enum constant
	 * @return the value previously set for that column, or {@code null} if none
	 */
	public <T> T getColumn(TestColumn column) {
		return getColumn(column.getSqlName());
	}

	/**
	 * The id generated by the database for this row.
	 *
	 * @return the id generated by the database for this row, once {@link TestDataBuilder#create()} has inserted it
	 */
	public Long getGeneratedId() {
		return generatedId;
	}

	void setGeneratedId(Long generatedId) {
		this.generatedId = generatedId;
	}

	/**
	 * Whether {@link TestDataBuilder#create()} has already inserted this row.
	 *
	 * @return {@code true} once inserted, {@code false} until then
	 */
	public boolean isAdded() {
		return added;
	}

	void markAdded() {
		this.added = true;
	}
}
